GET  http://localhost:3001/todoItems
Authorization: Bearer test
Content-Type: application/json
Access-Control-Allow-Origin: http://localhost:3000

{
 "id": 3,
 "text": "gdfggdfg",
 "isCompleted": false
}
###
